# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: energy.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'energy.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x65nergy.proto\x12\x06\x65nergy\"$\n\rEnergyRequest\x12\x13\n\x0b\x62uilding_id\x18\x01 \x01(\t\"N\n\x0e\x45nergyResponse\x12\x13\n\x0b\x62uilding_id\x18\x01 \x01(\t\x12\x17\n\x0f\x63onsumption_kwh\x18\x02 \x01(\x02\x12\x0e\n\x06status\x18\x03 \x01(\t2O\n\rEnergyService\x12>\n\rGetEnergyData\x12\x15.energy.EnergyRequest\x1a\x16.energy.EnergyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'energy_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENERGYREQUEST']._serialized_start=24
  _globals['_ENERGYREQUEST']._serialized_end=60
  _globals['_ENERGYRESPONSE']._serialized_start=62
  _globals['_ENERGYRESPONSE']._serialized_end=140
  _globals['_ENERGYSERVICE']._serialized_start=142
  _globals['_ENERGYSERVICE']._serialized_end=221
# @@protoc_insertion_point(module_scope)
